package com.marketap.sdk.model.internal

internal data class Device(
    val gaid: String? = null,
    val appSetId: String? = null,
    val appLocalId: String? = null,
    val os: String? = null,
    val osVersion: String? = null,
    val libraryVersion: String? = null,
    val model: String? = null,
    val manufacturer: String? = null,
    val brand: String? = null,
    val token: String? = null,
    val appVersion: String? = null,
    val appBuildNumber: String? = null,
    val browserName: String? = null,
    val browserVersion: String? = null,
    val userAgent: String? = null,
    val timezone: String? = null,
    val locale: String? = null,
    val screen: Screen? = null,
    val cpuArch: String? = null,
    val memoryTotal: Int? = null,
    val storageTotal: Int? = null,
    val batteryLevel: Int? = null,
    val isCharging: Boolean? = null,
    val networkType: String? = null,
    val carrier: String? = null,
    val hasSim: Boolean? = null,
    val maxTouchPoints: Int? = null,
    val camera: Boolean? = null,
    val microphone: Boolean? = null,
    val location: Boolean? = null,
    val notifications: Boolean? = null,
)
